remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
  
title: Real2Craft (Temp. Project Title)
description: Group 7$:$ Alfred Diego Cueva Valverde, Junhyun Kim, Kyle Kam, Robert Brandon Azarcon, Davin Doan 
